foreground = yes
pid =

[beam]
client = yes
accept = 127.0.0.1:9000
connect = GATEWAY_HOST:443
sni = GATEWAY_HOST
verifyChain = yes
CAfile = /etc/ssl/certs/ca-certificates.crt
checkHost = GATEWAY_HOST
sslVersionMin = TLSv1.2
